# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

imw_cpp <- function(x, k) {
    .Call('_IMW_imw_cpp', PACKAGE = 'IMW', x, k)
}

imw_update_cpp <- function(x, k, t, l) {
    .Call('_IMW_imw_update_cpp', PACKAGE = 'IMW', x, k, t, l)
}

